# Generated by Django 4.0.1 on 2022-06-09 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitacao',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='msg_day',
            name='mensagem',
            field=models.CharField(max_length=250),
        ),
    ]
