# Generated by Django 4.0.1 on 2022-03-21 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferr_report',
            name='id',
        ),
        migrations.AddField(
            model_name='ferr_report',
            name='ID',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
