# Generated by Django 4.0.1 on 2022-03-21 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_ferr_report_id_ferr_report_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ferr_report',
            old_name='ID',
            new_name='id',
        ),
    ]
