# Generated by Django 4.0.1 on 2022-06-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_solicitacao_options_alter_msg_day_mensagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg_day',
            name='mensagem',
            field=models.CharField(max_length=450),
        ),
    ]
